IM-30 Реализован скрипт на создание таблицы 'security_collection'
IPLATFORM-TECH/iplatform-moex-1 pull request #24
Opened 2022-08-11 20:31 UTC by romaRacoon

2022-08-15 20:42 UTC, XRave91 approved these changes

2022-08-16 05:50 UTC, a-s-eliseev requested changes

2022-08-16 05:50 UTC, a-s-eliseev commented on src/main/resources/application.yml
> -      ddl-auto: validate
а почему не validate?

2022-08-16 05:51 UTC, a-s-eliseev commented
и конфликт

2022-08-16 13:05 UTC, a-s-eliseev approved these changes

2022-08-16 13:05 UTC, merged