IM-43 Написан скрипт на заполнение таблицы duration
IPLATFORM-TECH/iplatform-moex-1 pull request #40
Opened 2022-08-12 18:52 UTC by fijirash

2022-08-12 19:44 UTC, Vasaluk approved these changes

2022-08-17 05:07 UTC, a-s-eliseev requested changes

2022-08-17 05:07 UTC, a-s-eliseev commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +<<<<<<< HEAD
нужно обновить обновить с мастера

2022-08-18 15:28 UTC, a-s-eliseev approved these changes

2022-08-18 15:28 UTC, merged