Im  18
IPLATFORM-TECH/iplatform-moex-1 pull request #42
Opened 2022-08-13 06:39 UTC by XRave91

enum BoardGroup

2022-08-13 11:30 UTC, Vasaluk approved these changes

2022-08-15 08:54 UTC, a-s-eliseev requested changes

2022-08-15 08:54 UTC, a-s-eliseev commented on src/main/java/space/eliseev/iplatformmoex/enums/BoardGroup.java
> +    private final String name;
использовать ломбок

2022-08-17 05:05 UTC, a-s-eliseev approved these changes

2022-08-17 05:05 UTC, merged